SectorsPerCluster   = 00dh
SavedSectorCount    = 00eh
FatCount            = 010h
StartSectorIndex    = 01ch
SectorCountPerFat   = 024h
RootClusterIndex    = 02ch

INODESIZE           = 20h
NAMEOFF             = 00h
FILETYPE            = 0bh
CLUSTERLOW          = 1ah
CLUSTERHIG          = 14h
FILESIZE            = 1ch

LONGNAME            = 0fh
MAXCLUSTER          = 0fffffff8h
LASTCLUSTER         = 0ffffffffh